export const API_BASE_URL = '/api'

export const endpoints = {
  health: `${API_BASE_URL}/health`,
  settings: `${API_BASE_URL}/settings`,
  validateBucket: `${API_BASE_URL}/settings/validate-bucket`,
  validateCredentials: `${API_BASE_URL}/settings/validate-credentials`,
  applySessionCredentials: `${API_BASE_URL}/settings/apply-session-credentials`,
  accounts: `${API_BASE_URL}/settings/accounts`,
  callerIdentity: `${API_BASE_URL}/settings/caller-identity`,
  detectStructure: `${API_BASE_URL}/settings/detect-structure`,
  discoverRegions: `${API_BASE_URL}/settings/discover-regions`,
  verifyLogs: `${API_BASE_URL}/settings/verify-logs`,
  sessions: `${API_BASE_URL}/sessions`,
  session: (id: string) => `${API_BASE_URL}/sessions/${id}`,
  sessionProcess: (id: string) => `${API_BASE_URL}/sessions/${id}/process`,
  sessionResume: (id: string) => `${API_BASE_URL}/sessions/${id}/resume`,
  sessionCancel: (id: string) => `${API_BASE_URL}/sessions/${id}/cancel`,
  sessionProgress: (id: string) => `${API_BASE_URL}/sessions/${id}/progress`,
  prompts: `${API_BASE_URL}/prompts`,
  prompt: (id: string) => `${API_BASE_URL}/prompts/${id}`,
  systemPrompt: `${API_BASE_URL}/prompts/system-prompt`,
  logviewerSessions: `${API_BASE_URL}/logviewer/sessions`,
  logviewerDisk: `${API_BASE_URL}/logviewer/disk`,
  metrics: `${API_BASE_URL}/metrics`,
  nlqueryExecute: `${API_BASE_URL}/nlquery/execute`,
  dashboard: `${API_BASE_URL}/dashboard`,
  dashboardFindings: `${API_BASE_URL}/dashboard/findings`,
  dashboardFindingDetail: (id: string) => `${API_BASE_URL}/dashboard/findings/${id}`,
  lookups: `${API_BASE_URL}/lookups`,
  investigateScenarios: `${API_BASE_URL}/investigate/scenarios`,
  investigateRun: `${API_BASE_URL}/investigate/run`,
  indexBuild: `${API_BASE_URL}/nlquery/index`,
  indexStatus: `${API_BASE_URL}/nlquery/index/status`,
} as const
